Feature 1 gr content version 2
Metatavu/noheva-api pull request #11
Opened 2023-04-13 14:10 UTC by kaeline

2023-04-27 09:58 UTC, anttileppa requested changes

2023-04-27 09:58 UTC, anttileppa commented on src/main/kotlin/fi/metatavu/noheva/api/ExhibitionDevicesGroupsApiImpl.kt
> +                    targetContentVersionExhibition = null
You should not be able to change targetContentVersionExhibition, the target exhibition needs to be derived from the targetRoom (as targetExhibition)

2023-04-27 09:58 UTC, anttileppa commented on src/main/kotlin/fi/metatavu/noheva/devices/ExhibitionDeviceGroupController.kt
> +    targetContentVersionExhibition: Exhibition?,
remove this, targetExhibition should be derived from targetRoom (as target exhibition)

2023-04-27 09:58 UTC, anttileppa commented on src/main/kotlin/fi/metatavu/noheva/devices/ExhibitionDeviceGroupController.kt
> +      targetContentVersionExhibition = targetContentVersionExhibition,
remove this, targetExhibition should be derived from targetDeviceGroup

2023-04-27 09:58 UTC, anttileppa commented on src/main/kotlin/fi/metatavu/noheva/exhibitions/ExhibitionController.kt
> +        targetContentVersionExhibition: Exhibition,
replace with targetExhibition

2023-04-27 09:58 UTC, anttileppa commented on src/main/kotlin/fi/metatavu/noheva/exhibitions/ExhibitionController.kt
> +                targetContentVersionExhibition = targetContentVersionExhibition,
replace with targetExhibition

2023-04-28 19:43 UTC, villejuutila requested changes
Requires some more investigation after these two reviews.

2023-04-28 19:43 UTC, villejuutila commented on src/main/kotlin/fi/metatavu/noheva/devices/ExhibitionDeviceGroupController.kt
> +   * @param contentVersions copy source group content versions
```suggestion
   * @param contentVersions copy source content versions
```

2023-04-28 19:43 UTC, villejuutila commented on src/main/kotlin/fi/metatavu/noheva/exhibitions/ExhibitionController.kt
> +        ): List<ExhibitionDeviceGroup> {
```suggestion
      ): List<ExhibitionDeviceGroup> {
```

2023-05-08 06:50 UTC, kaeline commented on src/main/kotlin/fi/metatavu/noheva/devices/ExhibitionDeviceGroupController.kt
> +    sourceGroupContentVersions.map(ContentVersion::id).map(idMapper::assignId)
fixed the name

2023-08-08 07:40 UTC, villejuutila approved these changes

2023-08-08 07:40 UTC, villejuutila commented on src/main/kotlin/fi/metatavu/noheva/api/ExhibitionDevicesGroupsApiImpl.kt
> +@Suppress ("unused")
```suggestion
@Suppress("unused")
```

2023-08-08 07:40 UTC, villejuutila commented on src/main/kotlin/fi/metatavu/noheva/api/ExhibitionDevicesGroupsApiImpl.kt
> +        val groupContentVersions = contentVersionController.listContentVersions(
```suggestion
        val contentVersions = contentVersionController.listContentVersions(
```
For clarity

2023-08-08 07:42 UTC, merged